version: '3.9'

services:
  couchbase:
    image: couchbase/server
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "11210:11210"
    deploy:
      resources:
        limits:
          memory: 3500M
        reservations:
          memory: 3500M