version: '3.3'

services:
  couchbase:
    image: couchbase:community
    ports:
      - "8091-8096:8091-8096"
      - "11210-11211:11210-11211"
    deploy:
      resources:
        limits:
          memory: 2800M
        reservations:
          memory: 2800M